### PR TITLE
added ci + make lint, fixed staticcheck complaints

### PR DESCRIPTION
**Pull request by metachris**
This PR adds a Makefile with `make lint` and `make test`, and fixes all complaints by `gofmt`, `go vet` and `[staticcheck](https://staticcheck.io/)`. Adds a Github CI workflow.

Linting does the following commands: 
```bash
gofmt -d ./
go vet ./...
staticcheck ./...
```

Not sure this is something you want, but thought I might as well offer it as contribution :)

### CODE REVIEW

**Comment by lightclient** [comment]
This is great, thank you! Any idea why the workflow isn't running here though?

**Comment by metachris** [comment]
Not sure, do you see a button to run it? That's sometimes the case for PRs of first-time contributors 🤔

**Comment by metachris** [comment]
oh, i see, because it uses `main`, not `master`. updating...

**Comment by metachris** [comment]
CI definitely ran on our repo: https://github.com/flashbots/mergemock/actions

I guess proto needs to manually run because I'm a first time contributor

**Comment by protolambda** [comment]
LGTM, let's see if it runs in the next PR

**Comment by lightclient** [comment]
Looks like it ran on `master` :+1:

**Pull request closed without merging**
